### PR TITLE
feat: Add api files & database related to attractions

### PR DESCRIPTION
**Pull request by jiashanchang**
彭彭老師晚安，我是張嘉珊，已完成本周任務如下，謝謝您！：

Part 1 - 1：將景點資料存放⾄資料庫，並將資料庫-attractions_data.sql 存放至 data 資料夾下
Part 1 - 2：開發旅遊景點 API，並將 API 檔案存放至 api 資料夾下
Part 1 - 3：將網站上線到 AWS EC2，測試網址如下：

http://35.77.165.151:3000/api/attractions?page=1

http://35.77.165.151:3000/api/attractions?page=0&keyword=藝文館所

http://35.77.165.151:3000/api/attractions?page=0&keyword=北

http://35.77.165.151:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Response format of http://35.77.165.151:3000/api/attraction/10 is incorrect.
2. `images` field of attraction should be an one-dimension array containing every attraction image URL. For example: `["Image URL 1", "Image URL 2", ...]`

Solve issues and re-request review.

**Comment by jiashanchang** [comment]
彭彭老師晚安，已修正景點圖片網址的表示方法，測試網址如下，謝謝您！：

http://35.77.165.151:3000/api/attraction/10

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Comment by jiashanchang** [comment]
彭彭老師您好，已重新請求審核，謝謝您！

**Review by cwpeng — COMMENTED** [review]
But second issue is still there. For example: http://35.77.165.151:3000/api/attractions?page=1

`images` field should be 1-dimension string array.

**Comment by jiashanchang** [comment]
彭彭老師晚安，已修正景點圖片網址的表示方法，測試網址如下，謝謝您！：

http://35.77.165.151:3000/api/attractions?page=1

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
