### PR TITLE
feat: RWD layout & add searchable function

### PR DESCRIPTION
**Pull request by jiashanchang**
彭彭老師晚安，我是張嘉珊，已完成本周任務如下，請審核，謝謝您！：

測試網址：http://35.77.165.151:3000/

Part 2 - 1：完成 RWD 靜態⾴⾯
Part 2 - 2：串接景點 API，取得並展⽰第⼀⾴的景點資訊
Part 2 - 3：完成⾃動載入後續⾴⾯的功能
Part 2 - 4：完成關鍵字搜尋功能
Part 2 - 5：完成景點分類關鍵字填入功能

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Aspect ratio of any images in your page should keep the same as original ones.
2. Your code will load the same page multiple times if we scroll down and up quickly. Try testing live URL, not just in your local machine.
未命名-2

**Comment by jiashanchang** [comment]
Good evening 彭彭,

I have adjusted the problems you said, please review, thanks!

http://35.77.165.151:3000/

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Aspect ratio of any images in your page should keep the same as original ones.
2. Content in header, keyvisual and attraction list should align with each other to left or right in any devices larger than 1200px.

**Comment by jiashanchang** [comment]
Good night 彭彭,

I have adjusted the problems you said, please review, thanks!

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
